import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ display: "flex", flexDirection: "column", height: "100vh" }}
      >
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
            color: "black",
          }}
        >
          <p>Header</p>
        </header>

        <div style={{ flex: 1, height: "100%", overflow: "auto" }}>
          {children}
        </div>

        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
            color: "black",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
