import "./globals.css";

import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial",
    template: "%s | Base Title",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          display: "flex",
          flexDirection: "column",
          height: "100vh",
          gap: "16px",
        }}
      >
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
            color: "black",
          }}
        >
          <div className="flex gap-4">
            <Link href="/" className="text-blue-500">
              Home
            </Link>
            <p>Header</p>
          </div>
        </header>

        <div style={{ flex: 1, height: "100%", overflow: "auto" }}>
          {children}
        </div>

        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
            color: "black",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
